//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MustacheMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publisher
    {
        public Publisher()
        {
            this.Book = new HashSet<Book>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Year { get; set; }
    
        public virtual ICollection<Book> Book { get; set; }
    }
}
